### ISSUE TITLE
Resizing Windows

### ISSUE THREAD

**Issue by nolanspecter** [giangngt/Chess-Project#4]
There's a problem with resizing the game windows back to normal after we already enlarged it

**Comment by giangngt** [comment]
As of current knowledge, I saw that problem only when running the program on my machine with Ubuntu

**Comment by NLTD1209** [comment]
Didn't see that problem when testing on my laptop.

**Comment by nolanspecter** [comment]
I tried both OS, only Ubuntu has that problem size the original size of the game window is not the same as on Windows. Should we fix this or should we focus on other functions first?

**Comment by giangngt** [comment]
I think this is not a critical problem, as the game is still function perfectly on Windows, we should focus more on other functions at the moment.

**Comment by nolanspecter** [comment]
I'll close the issue then
