### ISSUE TITLE
Should gitignore .pyc files

### ISSUE THREAD

**Issue by dinhanhx** [giangngt/Chess-Project#41]
## What are .pyc files?
[Here](https://github.com/giangngt/Chess-Project/tree/master/__pycache__)  and [here](https://github.com/giangngt/Chess-Project/tree/master/Game/__pycache__) are .pyc files. They are binary files.

## .gitignore
```
*.pyc
__pycache__
Game/__pycache__
```

**Comment by Huy-Ngo** [comment]
Agree. Even if they're not binary, caches should be ignored.

**Comment by nolanspecter** [comment]
Thanks. We will fix it
