### ISSUE TITLE
Check code with Pylint

### ISSUE THREAD

**Issue by nolanspecter** [giangngt/Chess-Project#45]
We should start using Pylint to check code in order to test our software. It can be useful for refactoring in the future

**Comment by giangngt** [comment]
Code is rated 5.40/10 in the beginning. I'll try to improve it.

**Comment by nolanspecter** [comment]
There are many errors with bad-whitespace. However when you look at the code some of the errors make the code easier to read and more pleasing on the eyes. You can mark them with #pylint:disable=bad-whitespace

**Comment by nolanspecter** [comment]
I tried commenting them. It improves the marking by quite a lot :D

**Comment by giangngt** [comment]
For better visibility, I used the command 'pylint --max-line-length=150', as I think the limit of 79 is not suitable for our project .
